### ISSUE TITLE
Multiple tracks replacement

### ISSUE THREAD

**Issue by esqwrf** [guzenco/USM_Audio_chunks_rewriter#1]
Hello, thank you for this great program, but there's a problem when replacing multiple tracks.
I tried to replace audio in Persona 4 Golden 64 PC USM's. This game uses track 0 for Japanese audio and track 1 for English. Both tracks are technically replaced if the end-result USM is demuxed, but the game fails to recognize track 1 no matter if it's HCA or ADX. It sees it only if the audio donor USM contains just the track 2.
Any help? Thanks in advance.

**Comment by guzenco** [comment]
Hello, try ``java -jar USM_Audio_chunks_rewriter.jar -group-size=2`` with [1.2](https://github.com/guzenco/USM_Audio_chunks_rewriter/releases/tag/1.2). This might help you.
If not, I need a donor USM file with 2 audio tracks to study its structure to create an alternative insertion algorithm.
I also need to know whether the game recognizes all the tracks in the donor file (not the file with the audio from the donor file). If not, I'm unlikely to be able to help.

**Comment by esqwrf** [comment]
> Hello, try `java -jar USM_Audio_chunks_rewriter.jar -group-size=2` with [1.2](https://github.com/guzenco/USM_Audio_chunks_rewriter/releases/tag/1.2). This might help you. If not, I need a donor USM file with 2 audio tracks to study its structure to create an alternative insertion algorithm. I also need to know whether the game recognizes all the tracks in the donor file (not the file with the audio from the donor file). If not, I'm unlikely to be able to help.

Well, I tried the new version, didn't help.

About the donor... Yes, both tracks are recognized by the game. And here's where it gets interesting: instead of using a custom donor file (made with Scaleform VE 4.6), I tried to use another vanilla game USM for this purpose. The end result is the same: both tracks are technically in place, but the game still doesn't see the second one.

[Here's both files on Mega, just in case](https://mega.nz/folder/sH5x2ALR#QR86VlkCUZKtJkaN6vIQXQ)

**Comment by esqwrf** [comment]
Oops, I accidentally closed the issue, sorry.

**Comment by guzenco** [comment]
[Here's](https://github.com/guzenco/USM_Audio_chunks_rewriter/releases/tag/1.2) the new version. I have improved the insertion algorithm, now it should work correctly with several audio tracks and in the resulting files all tracks should be recognized correctly by players.

**Comment by esqwrf** [comment]
> [Here's](https://github.com/guzenco/USM_Audio_chunks_rewriter/releases/tag/1.2) the new version. I have improved the insertion algorithm, now it should work correctly with several audio tracks and in the resulting files all tracks should be recognized correctly by players.

It's all working now, thank you again for this program and for quick troubleshooting!
