### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by esqwrf** [guzenco/USM_Audio_chunks_rewriter#2]
Hello, is it possible to add support for replacing tracks in specified slots only and/or track replacement with standalone HCA/ADX files?

**Comment by guzenco** [comment]
`support for replacing tracks in specified slots` - was implemented in the [latest version](https://github.com/guzenco/USM_Audio_chunks_rewriter/releases/tag/1.3).
`track replacement with standalone HCA/ADX files` - this is a rather complex task that requires a significant change in the current logic, so it won't be implemented.

**Comment by esqwrf** [comment]
Thank you, everything works great!
