### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by ARandomGuy231** [guzenco/USM_Audio_chunks_rewriter#3]
Just tried following the instructions on the page and I got this error after saying start
![image](https://github.com/user-attachments/assets/3d77a7b2-fb99-45b0-8269-0b2591a1631e)

There is one USM in each of these folders, one with the audio I want and one with one I want to swap out

**Comment by guzenco** [comment]
You are using paths in quotes and this is causing the error. Using paths without quotes should fix this error.

**Comment by ARandomGuy231** [comment]
Weird, but that fixed it!
Thanks for that!
